import { useCallback, useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import api from '../lib/api';

export default function Audit() {
  const [logs, setLogs] = useState([]); const [action, setAction] = useState('');
  const load = useCallback(() => api.get('/users/admin/audit', { params: { limit: 100, action: action || undefined } }).then(({ data }) => setLogs(data.logs)), [action]);
  useEffect(() => { load(); }, [load]);
  const download = async () => { const response = await api.get('/users/admin/audit/export', { params: { action: action || undefined }, responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = `docflow-audit-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); };
  return <div className="min-h-screen bg-slate-100"><PageHeader title="Audit Log" backTo="/admin-dashboard"/><main className="mx-auto max-w-6xl px-6 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Security audit log</h1><p className="mt-2 text-slate-500">Admin-only access to recorded account, appointment, and queue changes.</p></div><div className="flex gap-2"><input value={action} onChange={(e) => setAction(e.target.value)} className="rounded-xl border px-3 py-2" placeholder="Exact action filter"/><button onClick={load} className="rounded-xl border px-4 py-2 font-semibold">Filter</button><button onClick={download} className="rounded-xl bg-blue-600 px-4 py-2 font-semibold text-white">Export CSV</button></div></div><section className="mt-7 overflow-x-auto rounded-3xl bg-white p-6 shadow"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Time</th><th>Actor</th><th>Role</th><th>Action</th><th>Entity</th></tr></thead><tbody>{logs.map((log) => <tr key={log._id} className="border-b"><td className="py-3">{new Date(log.createdAt).toLocaleString()}</td><td>{log.actor?.email || 'System'}</td><td>{log.actor?.role || 'system'}</td><td className="font-semibold">{log.action}</td><td>{log.entity} {log.entityId?.slice(-6)}</td></tr>)}</tbody></table></section></main></div>;
}
