import { ArrowLeft, Check, Eye, EyeOff, KeyRound, LockKeyhole, Mail, RefreshCw, ShieldCheck, Stethoscope } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import api from '../lib/api';

const storageKey = 'docflow-password-reset';
const readFlow = () => { try { return JSON.parse(sessionStorage.getItem(storageKey)) || {}; } catch { return {}; } };
const saveFlow = value => sessionStorage.setItem(storageKey, JSON.stringify(value));

function Shell({ step, children }) {
  return <div className="soft-grid flex min-h-screen items-center justify-center bg-slate-100 px-5 py-12"><div className="app-card w-full max-w-xl rounded-3xl p-7 sm:p-10"><div className="flex items-center justify-between"><Link to="/login" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-indigo-600"><ArrowLeft size={16}/>Back to login</Link><span className="brand-mark"><Stethoscope size={18}/></span></div><div className="mt-8 flex gap-2">{[1,2,3].map(item=><span key={item} className={`h-1.5 flex-1 rounded-full ${item <= step ? 'bg-indigo-600' : 'bg-slate-200'}`}/>)}</div>{children}</div></div>;
}

export default function ForgotPasswordFlow() {
  const location = useLocation(); const navigate = useNavigate();
  const step = location.pathname.endsWith('/verify') ? 2 : location.pathname.endsWith('/reset') ? 3 : 1;
  const [flow,setFlow] = useState(readFlow); const [email,setEmail] = useState(flow.email || ''); const [otp,setOtp] = useState('');
  const [form,setForm] = useState({password:'',confirmPassword:''}); const [show,setShow] = useState(false);
  const [seconds,setSeconds] = useState(() => Math.max(0,Math.ceil((new Date(flow.expiresAt||0).getTime()-Date.now())/1000)));
  const [message,setMessage] = useState(''); const [error,setError] = useState(false); const [loading,setLoading] = useState(false);

  useEffect(()=>{if(step===2&&!flow.email)navigate('/forgot-password',{replace:true});if(step===3&&(!flow.email||!flow.resetToken))navigate('/forgot-password',{replace:true})},[step,flow,navigate]);
  useEffect(()=>{if(step!==2)return undefined;const update=()=>setSeconds(Math.max(0,Math.ceil((new Date(flow.expiresAt||0).getTime()-Date.now())/1000)));update();const timer=setInterval(update,1000);return()=>clearInterval(timer)},[step,flow.expiresAt]);
  const requestOtp=async event=>{event?.preventDefault();setLoading(true);setMessage('');try{const target=step===2?flow.email:email;const{data}=await api.post('/auth/password/forgot',{email:target});const next={email:target.trim().toLowerCase(),expiresAt:data.expiresAt};saveFlow(next);setFlow(next);setOtp('');setError(false);setMessage(data.message);navigate('/forgot-password/verify')}catch(err){const data=err.response?.data;if(data?.expiresAt){const next={email:(step===2?flow.email:email).trim().toLowerCase(),expiresAt:data.expiresAt};saveFlow(next);setFlow(next)}setError(true);setMessage(data?.message||'Unable to send a reset code.')}finally{setLoading(false)}};
  const verify=async event=>{event.preventDefault();setLoading(true);setMessage('');try{const{data}=await api.post('/auth/password/verify-otp',{email:flow.email,otp});const next={...flow,resetToken:data.resetToken};saveFlow(next);setFlow(next);setError(false);navigate('/forgot-password/reset')}catch(err){setError(true);setMessage(err.response?.data?.message||'Unable to verify the code.')}finally{setLoading(false)}};
  const reset=async event=>{event.preventDefault();setLoading(true);setMessage('');try{const{data}=await api.post('/auth/password/reset',{email:flow.email,resetToken:flow.resetToken,...form});sessionStorage.removeItem(storageKey);setError(false);setMessage(data.message);setTimeout(()=>navigate('/login'),1200)}catch(err){setError(true);setMessage(err.response?.data?.message||'Unable to reset your password.')}finally{setLoading(false)}};
  const changeEmail=()=>{sessionStorage.removeItem(storageKey);setFlow({});setOtp('');setMessage('');navigate('/forgot-password')};
  const notice=message&&<div className={`mt-5 rounded-xl border p-3.5 text-sm font-medium ${error?'border-red-100 bg-red-50 text-red-700':'border-green-100 bg-green-50 text-green-700'}`}>{message}</div>;

  if(step===1)return <Shell step={1}><span className="mt-8 grid h-12 w-12 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><KeyRound size={23}/></span><p className="eyebrow mt-5">Account recovery</p><h1 className="page-title mt-2 text-4xl font-extrabold">Forgot your password?</h1><p className="mt-3 text-slate-500">Enter your account email and we’ll send a secure reset code.</p>{notice}<form onSubmit={requestOtp}><label className="mt-7 block text-sm font-bold text-slate-700">Email address<div className="relative mt-2"><Mail className="absolute left-4 top-3.5 text-slate-400" size={18}/><input required autoFocus type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-xl border py-3 pl-12 pr-4" placeholder="you@example.com"/></div></label><button disabled={loading} className="mt-7 w-full rounded-xl bg-indigo-600 py-3.5 font-bold text-white shadow-lg shadow-indigo-200 disabled:opacity-60">{loading?'Sending code…':'Send reset code'}</button></form></Shell>;
  if(step===2)return <Shell step={2}><span className="mt-8 grid h-12 w-12 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><ShieldCheck size={23}/></span><h1 className="page-title mt-5 text-4xl font-extrabold">Verify your email</h1><p className="mt-3 text-slate-500">Enter the 6-digit reset code sent to <b className="text-slate-700">{flow.email}</b>.</p>{notice}<form onSubmit={verify}><input aria-label="Verification code" required autoFocus inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength="6" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} className="mt-7 w-full rounded-xl border px-4 py-3 text-center text-2xl font-extrabold tracking-[.5em]" placeholder="000000"/><div className={`mt-4 rounded-xl p-3 text-center text-sm font-bold ${seconds?'bg-indigo-50 text-indigo-600':'bg-amber-50 text-amber-700'}`}>{seconds?`Code expires in ${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`:'This code has expired'}</div><button disabled={loading||otp.length!==6||seconds===0} className="mt-5 w-full rounded-xl bg-indigo-600 py-3.5 font-bold text-white disabled:opacity-50">{loading?'Verifying…':'Verify code'}</button></form><div className="mt-5 grid gap-3 sm:grid-cols-2"><button disabled={seconds>0||loading} onClick={requestOtp} className="flex items-center justify-center gap-2 rounded-xl border px-4 py-3 text-sm font-bold text-slate-600 disabled:opacity-40"><RefreshCw size={16}/>Resend OTP</button><button onClick={changeEmail} className="flex items-center justify-center gap-2 rounded-xl border px-4 py-3 text-sm font-bold text-slate-600"><Mail size={16}/>Change email</button></div></Shell>;
  return <Shell step={3}><span className="mt-8 grid h-12 w-12 place-items-center rounded-2xl bg-green-50 text-green-600"><Check size={23}/></span><p className="eyebrow mt-5">Email verified</p><h1 className="page-title mt-2 text-4xl font-extrabold">Set a new password</h1><p className="mt-3 text-slate-500">Choose a strong password you haven’t used before.</p>{notice}<form onSubmit={reset}><label className="mt-7 block text-sm font-bold text-slate-700">New password<div className="relative mt-2"><LockKeyhole className="absolute left-4 top-3.5 text-slate-400" size={18}/><input required minLength="8" type={show?'text':'password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="w-full rounded-xl border py-3 pl-12 pr-12" placeholder="At least 8 characters"/><button type="button" aria-label="Toggle password visibility" onClick={()=>setShow(v=>!v)} className="absolute right-4 top-3.5 text-slate-400">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><label className="mt-5 block text-sm font-bold text-slate-700">Confirm new password<input required minLength="8" type={show?'text':'password'} value={form.confirmPassword} onChange={e=>setForm({...form,confirmPassword:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label>{form.confirmPassword&&form.password!==form.confirmPassword&&<p className="mt-2 text-sm font-medium text-red-600">Passwords do not match.</p>}<button disabled={loading||form.password!==form.confirmPassword} className="mt-7 w-full rounded-xl bg-indigo-600 py-3.5 font-bold text-white disabled:opacity-50">{loading?'Updating password…':'Reset password'}</button></form></Shell>;
}
