import { ArrowRight, Bot, CalendarCheck, Check, Clock3, ShieldCheck, Sparkles, Stethoscope, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';

const features = [
  [CalendarCheck, 'Effortless booking', 'Find the right doctor and reserve a time in a few focused steps.'],
  [Clock3, 'Live queue tracking', 'See your place in line and estimated wait time without staying at reception.'],
  [Bot, 'Smart guidance', 'Describe symptoms and get directed to the most relevant specialty.'],
];

export default function Home() { return <div className="min-h-screen bg-white text-slate-900">
  <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-6"><Link to="/" className="flex items-center gap-3"><span className="brand-mark"><Stethoscope size={20}/></span><span className="text-xl font-extrabold tracking-tight">DocFlow</span></Link><nav className="flex items-center gap-1 sm:gap-3"><Link to="/login" className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50">Log in</Link><Link to="/register" className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-indigo-200 hover:-translate-y-0.5 hover:bg-indigo-700 sm:px-5">Get started</Link></nav></div></header>
  <main>
    <section className="soft-grid relative overflow-hidden"><div className="absolute left-1/2 top-0 h-96 w-96 -translate-x-1/2 rounded-full bg-indigo-200/40 blur-3xl"/><div className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 py-20 sm:px-6 lg:grid-cols-[1.08fr_.92fr] lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-white px-3.5 py-2 text-sm font-bold text-indigo-600 shadow-sm"><Sparkles size={15}/>Your care, beautifully coordinated</div><h1 className="page-title mt-7 max-w-3xl text-5xl font-extrabold leading-[1.05] sm:text-6xl lg:text-7xl">Healthcare that keeps <span className="text-indigo-600">moving.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Book visits, follow live queues, and manage every step of care from one calm, connected workspace.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/register" className="flex items-center gap-2 rounded-xl bg-indigo-600 px-6 py-3.5 font-bold text-white shadow-xl shadow-indigo-200 hover:-translate-y-0.5 hover:bg-indigo-700">Create free account <ArrowRight size={18}/></Link><Link to="/login" className="rounded-xl border border-slate-200 bg-white px-6 py-3.5 font-bold text-slate-700 shadow-sm hover:border-indigo-200">Open your workspace</Link></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-2 text-sm font-medium text-slate-500">{['Role-based access','Fast appointment flow','Real-time updates'].map(x=><span key={x} className="flex items-center gap-2"><Check className="text-emerald-500" size={16}/>{x}</span>)}</div></div>
    <div className="relative"><div className="absolute -inset-8 rounded-full bg-indigo-200/30 blur-3xl"/><div className="app-card relative rounded-[2rem] p-4 sm:p-6"><div className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-indigo-300">Today’s appointment</p><h2 className="mt-2 text-2xl font-bold">Dr. Sarah Ahmed</h2><p className="mt-1 text-slate-400">Cardiology · 10:30 AM</p></div><span className="rounded-full bg-emerald-400/15 px-3 py-1.5 text-xs font-bold text-emerald-300">Confirmed</span></div><div className="mt-10 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/8 p-4"><p className="text-xs text-slate-400">Now serving</p><p className="mt-2 text-4xl font-bold">08</p></div><div className="rounded-2xl bg-indigo-500 p-4"><p className="text-xs text-indigo-100">Your number</p><p className="mt-2 text-4xl font-bold">11</p></div></div><div className="mt-4 flex items-center gap-3 rounded-2xl bg-white/8 p-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-400/15 text-emerald-300"><Clock3 size={20}/></div><div><p className="text-sm font-bold">About 15 minutes</p><p className="text-xs text-slate-400">3 patients ahead of you</p></div></div></div><div className="grid grid-cols-2 gap-3 pt-4 sm:grid-cols-3"><div className="rounded-2xl bg-indigo-50 p-4 text-indigo-700"><ShieldCheck/><p className="mt-3 text-sm font-bold">Secure</p></div><div className="rounded-2xl bg-emerald-50 p-4 text-emerald-700"><UsersRound/><p className="mt-3 text-sm font-bold">Connected</p></div><div className="col-span-2 rounded-2xl bg-amber-50 p-4 text-amber-700 sm:col-span-1"><Sparkles/><p className="mt-3 text-sm font-bold">Simple</p></div></div></div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-6"><div className="max-w-2xl"><p className="eyebrow">Everything in one place</p><h2 className="page-title mt-3 text-3xl font-extrabold sm:text-4xl">Less waiting. More caring.</h2><p className="mt-4 text-slate-600">Designed for patients and care teams to get important work done without the usual friction.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{features.map(([Icon,title,copy])=><article key={title} className="app-card rounded-3xl p-6"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><Icon size={23}/></span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-2 leading-7 text-slate-600">{copy}</p></article>)}</div></section>
  </main>
  <footer className="border-t border-slate-200"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-6 py-7 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span className="font-bold text-slate-700">DocFlow</span><span>© 2026 DocFlow. Smarter healthcare operations.</span></div></footer>
</div> }
