import { useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import api from '../lib/api';

export default function MedicalRecords() {
  const [history, setHistory] = useState({ records: [], prescriptions: [] });
  useEffect(() => { api.get('/clinical/history/mine').then(({ data }) => setHistory(data)); }, []);
  return <div className="min-h-screen bg-slate-100"><PageHeader title="Medical Records" backTo="/dashboard"/><main className="mx-auto max-w-6xl px-6 py-10"><div className="mt-7 grid gap-6 lg:grid-cols-2"><section className="space-y-4"><h2 className="text-xl font-bold">Medical records</h2>{history.records.map((record) => <article key={record._id} className="rounded-3xl bg-white p-6 shadow"><p className="text-sm text-slate-500">{record.appointment?.appointmentDate} · {record.doctor?.name}</p><h3 className="mt-2 text-xl font-bold">{record.diagnosis}</h3>{record.symptoms?.length > 0 && <p className="mt-3"><b>Symptoms:</b> {record.symptoms.join(', ')}</p>}{record.allergies?.length > 0 && <p className="mt-2 text-red-600"><b>Allergies:</b> {record.allergies.join(', ')}</p>}<div className="mt-3 grid grid-cols-2 gap-2 text-sm">{Object.entries(record.vitals || {}).filter(([, value]) => value != null && value !== '').map(([key, value]) => <span key={key} className="rounded-xl bg-slate-50 p-3"><b>{key}</b><br/>{value}</span>)}</div>{record.labResults?.map((result) => <p key={result._id} className="mt-2 rounded-xl bg-blue-50 p-3 text-sm"><b>{result.name}:</b> {result.result} {result.unit} <span className="text-slate-500">({result.referenceRange})</span></p>)}</article>)}{history.records.length === 0 && <p className="rounded-2xl bg-white p-6 text-slate-500">No medical records yet.</p>}</section><section className="space-y-4"><h2 className="text-xl font-bold">Prescriptions</h2>{history.prescriptions.map((prescription) => <article key={prescription._id} className="rounded-3xl bg-white p-6 shadow"><p className="text-sm text-slate-500">{prescription.appointment?.appointmentDate} · {prescription.doctor?.name}</p><div className="mt-4 space-y-3">{prescription.medicines.map((medicine) => <div key={medicine._id} className="rounded-2xl bg-green-50 p-4"><b>{medicine.name} · {medicine.dosage}</b><p className="mt-1 text-sm">{medicine.frequency} for {medicine.duration}</p>{medicine.instructions && <p className="mt-1 text-sm text-slate-600">{medicine.instructions}</p>}</div>)}</div>{prescription.advice && <p className="mt-4"><b>Advice:</b> {prescription.advice}</p>}{prescription.followUpDate && <p className="mt-2 text-blue-600"><b>Follow up:</b> {prescription.followUpDate}</p>}</article>)}{history.prescriptions.length === 0 && <p className="rounded-2xl bg-white p-6 text-slate-500">No structured prescriptions yet.</p>}</section></div></main></div>;
}
