import { useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import api from '../lib/api';
import { getUser } from '../lib/auth';

export default function Security() {
  const [user, setUser] = useState(getUser()); const [sessions, setSessions] = useState([]); const [challenge, setChallenge] = useState(null); const [otp, setOtp] = useState(''); const [password, setPassword] = useState(''); const [msg, setMsg] = useState('');
  const load = () => api.get('/auth/sessions').then(({ data }) => setSessions(data.sessions)); useEffect(() => { load(); }, []);
  const enable = async () => { try { const { data } = await api.post('/auth/mfa/enable'); setChallenge(data.challengeId); setMsg(data.message); } catch (error) { setMsg(error.response?.data?.message || 'Unable to enable MFA.'); } };
  const verify = async () => { try { const { data } = await api.post('/auth/mfa/verify', { challengeId: challenge, otp }); setUser(data.user); localStorage.setItem('user', JSON.stringify(data.user)); setChallenge(null); setMsg(data.message); } catch (error) { setMsg(error.response?.data?.message || 'Unable to verify MFA.'); } };
  const disable = async () => { try { const { data } = await api.post('/auth/mfa/disable', { password }); setUser(data.user); localStorage.setItem('user', JSON.stringify(data.user)); setPassword(''); setMsg(data.message); } catch (error) { setMsg(error.response?.data?.message || 'Unable to disable MFA.'); } };
  const revoke = async (session) => { if (session.current || !confirm('End this device session?')) return; await api.delete(`/auth/sessions/${session.id}`); load(); };
  return <div className="min-h-screen bg-slate-100"><PageHeader title="Account Security"/><main className="mx-auto max-w-4xl space-y-7 px-6 py-10">{msg && <div className="rounded-xl bg-blue-50 p-3 text-blue-700">{msg}</div>}<section className="rounded-3xl bg-white p-8 shadow"><h1 className="text-3xl font-bold">Multi-factor authentication</h1><p className="mt-2 text-slate-500">Protect sign-in with a one-time code sent to your verified email.</p>{challenge ? <div className="mt-5 flex gap-3"><input inputMode="numeric" maxLength="6" value={otp} onChange={(e) => setOtp(e.target.value.replace(/\D/g, ''))} className="rounded-xl border px-4 py-3" placeholder="6-digit code"/><button onClick={verify} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Verify and enable</button></div> : user?.mfaEnabled ? <div className="mt-5 flex gap-3"><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="rounded-xl border px-4 py-3" placeholder="Current password"/><button onClick={disable} className="rounded-xl border border-red-200 px-5 py-3 font-semibold text-red-600">Disable MFA</button></div> : <button onClick={enable} className="mt-5 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Enable MFA</button>}</section><section className="rounded-3xl bg-white p-8 shadow"><h2 className="text-2xl font-bold">Active device sessions</h2><div className="mt-5 space-y-3">{sessions.map((session) => <div key={session.id} className="flex items-center justify-between gap-4 rounded-2xl bg-slate-50 p-4"><div><b>{session.current ? 'This device' : session.device}</b><p className="mt-1 text-xs text-slate-500">Last active {new Date(session.lastUsedAt).toLocaleString()} · {session.ip || 'IP unavailable'}</p></div>{!session.current && <button onClick={() => revoke(session)} className="rounded-xl border px-4 py-2 font-semibold text-red-600">End session</button>}</div>)}</div></section></main></div>;
}
