const express = require('express');
const { protect, authorize } = require('../middleware/auth');
const c = require('../controllers/appointmentController');
const router = express.Router();
router.use(protect);
router.post('/', authorize('patient'), c.createAppointment);
router.get('/mine', authorize('patient'), c.patientAppointments);
router.get('/all', authorize('admin', 'receptionist'), c.allAppointments);
router.get('/doctor/mine', authorize('doctor'), c.doctorAppointments);
router.post('/reminders/run', authorize('admin', 'receptionist'), c.runReminders);
router.get('/reports/summary', authorize('admin'), c.reports);
router.get('/reports/export', authorize('admin'), c.exportAppointments);
router.get('/queue/:doctorId/:date', authorize('admin', 'receptionist', 'doctor'), c.queueStatus);
router.patch('/queue/:doctorId/:date', authorize('admin', 'receptionist', 'doctor'), c.controlQueue);
router.get('/:id', c.getById);
router.get('/:id/calendar', c.calendar);
router.put('/:id/approve', authorize('admin', 'receptionist'), c.approve);
router.put('/:id/advance', authorize('admin', 'receptionist', 'doctor'), c.advanceQueue);
router.put('/:id/doctor-update', authorize('doctor'), c.doctorUpdate);
router.put('/:id/cancel', authorize('patient'), c.cancel);
router.put('/:id/reschedule', authorize('patient'), c.reschedule);
router.put('/:id/rejoin', authorize('admin', 'receptionist'), c.rejoinQueue);
router.put('/:id/no-show', authorize('admin', 'receptionist', 'doctor'), c.markNoShow);
router.put('/:id/reassign', authorize('admin', 'receptionist'), c.reassignDoctor);
module.exports = router;
