const express = require('express');
const { requestRegistrationOtp, verifyRegistrationOtp, completeRegistration, requestPasswordResetOtp, verifyPasswordResetOtp, resetPassword, login, me, verifyMfa, requestMfaEnable, disableMfa, sessions, logout, revokeSession, logoutAll } = require('../controllers/authController');
const { protect } = require('../middleware/auth');
const router = express.Router();
router.post('/register/request-otp', requestRegistrationOtp);
router.post('/register/verify-otp', verifyRegistrationOtp);
router.post('/register/complete', completeRegistration);
router.post('/password/forgot', requestPasswordResetOtp);
router.post('/password/verify-otp', verifyPasswordResetOtp);
router.post('/password/reset', resetPassword);
router.post('/login', login);
router.post('/mfa/verify', verifyMfa);
router.get('/me', protect, me);
router.post('/mfa/enable', protect, requestMfaEnable);
router.post('/mfa/disable', protect, disableMfa);
router.get('/sessions', protect, sessions);
router.post('/logout', protect, logout);
router.post('/logout-all', protect, logoutAll);
router.delete('/sessions/:id', protect, revokeSession);
module.exports = router;
