const express = require('express');
const { protect, authorize } = require('../middleware/auth');
const { updateMe, adminStats, listUsers, createStaff, updateStaff, deactivateStaff, publicDoctors, doctorAvailability, updateAvailability, auditLogs, requestEmailChange, verifyEmailChange, exportAuditLogs, exportMyData, deleteMyAccount, updateNotificationPreferences, resetAllData } = require('../controllers/userController');
const router = express.Router();
router.get('/doctors', publicDoctors);
router.get('/doctors/:id/availability', doctorAvailability);
router.put('/me', protect, updateMe);
router.post('/me/email/request', protect, requestEmailChange);
router.post('/me/email/verify', protect, verifyEmailChange);
router.get('/me/export', protect, exportMyData);
router.delete('/me', protect, deleteMyAccount);
router.put('/me/notifications', protect, updateNotificationPreferences);
router.put('/me/availability', protect, authorize('doctor'), updateAvailability);
router.get('/admin/stats', protect, authorize('admin'), adminStats);
router.get('/admin/users', protect, authorize('admin'), listUsers);
router.post('/admin/staff', protect, authorize('admin'), createStaff);
router.put('/admin/staff/:id', protect, authorize('admin'), updateStaff);
router.patch('/admin/staff/:id/toggle', protect, authorize('admin'), deactivateStaff);
router.get('/admin/audit', protect, authorize('admin'), auditLogs);
router.get('/admin/audit/export', protect, authorize('admin'), exportAuditLogs);
router.post('/admin/reset-data', protect, authorize('admin'), resetAllData);
module.exports = router;
